### ISSUE TITLE
Problem when sign in on iPhone

### ISSUE THREAD

**Issue by pongponk** [ContactTracing-app/Frontend#37] opened 2020-03-28 12:59 UTC
on IOS devices, on successful login, the OAUTH redirect comes back to the default firebase hosting url… but there's nothing there because we're hosting externally on a custom domain.

![image](https://user-images.githubusercontent.com/25208986/77823502-7e817a80-70f3-11ea-9d55-803478fab783.png)

**Comment by mmmoli** [comment] 2020-03-28 21:23
Fixed with the new `auth.contacttracing.app` subdomain. 🎉 😎

**Comment by mmmoli** [comment] 2020-03-29 16:59
@firacloudtech @kavyvetri Here's where we're at.

# Background
Firebase gives you a domain name for every project. It wants you to host your project there (probably so that they can charge hosting costs).

We're not using hosting. Our project is hosted on [netlify](https://www.netlify.com/). It builds our project and serves the resulting `build/`. Netlify is also responsible for our DNS.

# Problem
Users are reporting:

> As a new user
when I visit the profile page
and I try to log in
then I see a blank webpage

# Issue
You're app needs a `handler` to receive the auth token back from the log-in provider and convert it to a firebase user. This is handled automatically for you in FB. The handler is hidden but it's there, behind the scenes at `<YOUR_DOMAIN>/__auth/handler`.

Problem 1: On successful sign-in the app is directing to the default FB domain (the one that doesn't have anything there to serve) so users see nothing (see url in screenshot above).

Problem 2: We can't redirect to the real url because  netlify is serving the app – there's definitely no handler there so we'll see the same issue.

# Attempted fix

With much Googling, I decided we had to give into FB hosting. I didn't want to give-up the A records to FB, so I created a subdomain `auth.contacttracing.app` which points with A records to FB instead.

Now FB has a domain that it is in control of and therefore it'll provide the auth handler we need.

If you sign-in now, you'll see `auth.contacttracing.app` mentioned so it's hooked-up and working as expected…

# But it's now…
Now the issue is that users are arriving at the fancy new subdomain, but still being presented with a blank page because there's still nothing there.

# Plan
I'm going to throw-up a page, hosted by FB, to redirect users with a html meta tag. Come to think of it, you do see this quite a lot 🤔

**Comment by mmmoli** [comment] 2020-03-29 17:34
so my "plan" doesn't work either as if you visit the route directly (like, if you were facebook passing back an access token) you see the same issue users are reporting: a blank page:

https://auth.contacttracing.app/__/auth/handler

**Closed** 2020-03-29 18:31 UTC
Labels: bug

**Comment by mmmoli** [comment] 2020-04-06 18:04
@all-contributors please add @kavyvetri for code

**Comment by mmmoli** [comment] 2020-04-06 18:08
@all-contributors please add @kavyvetri for code

**Comment by mmmoli** [comment] 2020-04-06 18:08
@all-contributors please add @kavyvetri for code
